spring:
  datasource:
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 1
      maximum-pool-size: 10
      pool-name: plataforma-database-pool
      auto-commit: false
      connection-timeout: 30000
    url: jdbc:postgresql://db:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        ddl-auto: create
        show-sql: 'true'
    database-platform: org.hibernate.dialect.PostgreSQLDialect