version: '3.1'

services:
  db:
    image: postgres:13
    volumes:
      - dbbase:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: appramon
volumes:
  dbbase: